### ISSUE TITLE
"cursor size" too small

### ISSUE THREAD

**Issue by sjvrensburg** [qtilities/magnifiqus#3]
I am using Magnifiqus with the option "Show cursor" enabled. The rectangle that indicates where the cursor is in the enlarged view is quite small and difficult to see. This might be because I'm using a HiDPI display.

Is it possible to have a setting where the user can adjust the size of this rectangle?

**Comment by redtide** [comment]
Hello! I have no objections about it, do you want to try to make a PR to add such feature? I guess it will require some new preference dialog where to set the cursor size. Otherwise I'll give it a look later.

**Comment by redtide** [comment]
I did something in the [prefs-dialog](/redtide/magnifiqus/tree/prefs-dialog) branch if you want to give it a try.

**Comment by sjvrensburg** [comment]
> I did something in the [prefs-dialog](/redtide/magnifiqus/tree/prefs-dialog) branch if you want to give it a try.

Thank you. I'll have to have a look at it over the weekend. I really appreciate that you took the time to do that, because GUI C++ is outside of my wheelhouse. I doubt I would have been able to modify your code effectively.

**Comment by sjvrensburg** [comment]
OK, I just tested it and it works perfectly! Thank you so much. This is going to make my life a lot easier.

**Comment by redtide** [comment]
Good! Then I'll merge it to master.
